### ISSUE TITLE
VSIX's validation rule mismatch with MySQL

### ISSUE THREAD

**Issue by makotoitomeitetsucom** [R4ND3LL/EdmxRuler#11]
Konnichiwa (Hello) Mark.
I found another one.

I created entities from the MySqlDatabase with the command "dotnet ef dbcontext scaffold".
A rule file was generated like below .

```
{
  "Name": "EfCoreContext",
  "PreserveCasingUsingRegex": false,
  "IncludeUnknownSchemas": true,
  "SplitEntityTypeConfigurations": false,
  "Schemas": [
    {
      "SchemaName": "",
      "IncludeUnknownTables": true,
      "IncludeUnknownViews": true,
      "Namespace": null,
      "Entities": [
        {
          "Name": "tables",
          "EntityName": "Table",
          "IncludeUnknownColumns": true,
          "Properties": [
            {
              "Name": "col1",
              "PropertyName": "Col1"
            }         ]
        }
      ]
    }
  ]
}
```

I opened this file by the VS extension.

![opened](https://user-images.githubusercontent.com/25972784/213372511-60768023-76d2-43e8-a423-577bb4f02153.png)

(The dialog was appeared with empty scheme name.)

I tried to save this dialog without any modification, a validation error was occurred like below.
![beforesaving](https://user-images.githubusercontent.com/25972784/213372989-70df87b1-1cf2-41c4-b79f-d0f3cd63288f.png)

I think this validation rule isn't correct for MySQL.
(When I filled the SchemeName manually, "dotnet ef dbcontext scaffold" was failed caused by table not found error... May be empty scheme name is necessary for MySQL)

**Comment by R4ND3LL** [comment]
Spinning up another release v1.2.6 (building now).  Should fix this no problem.  Thanks!
