### ISSUE TITLE
Enums are showing a '+' instead of a '.'

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#12]
The New Type field is a great feature for enums but I see an issue:
![image](https://user-images.githubusercontent.com/119625172/214435920-fe9d233b-c057-4189-9e1d-df0d74624755.png)

All my enum mappings have the '+' instead of '.'

**Comment by R4ND3LL** [comment]
Fixed in v1.2.7, and latest VSIX.   

Unfortunately it will not correct values that  already have the +.  You may have to either regenerate a rule file or correct manually.
