### ISSUE TITLE
Rule Editor opens with Name field empty

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#13]
After I run scaffolding, almost every time I open the DB Context Rule Editor, I have to specify the name field:
![image](https://user-images.githubusercontent.com/119625172/214481187-4b49fb8b-4e31-4c28-9738-e7a4cf19b6e6.png)

On rare occasion it will stay populated but 90+% of the time it is empty

Also, even though I am setting the Name to OptiCAMEntities, the result file is OptiCam6Context.cs:
![image](https://user-images.githubusercontent.com/119625172/214579008-2c3f1c21-8b29-4a90-9581-38ef61817e0f.png)

**Comment by R4ND3LL** [comment]
The context name is being written based on the scaffolding args that you use (when you specify "-c").

It ends up blank when the context name is missing from your args.  I fixed this issue.

Also added the feature to SET the context name from the rule file if the -c was missing.

This will appear in v1.2.9 (which is building now).
