### ISSUE TITLE
New Name is ignored if New Type is set

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#14]
If you change the New Name mapping on a field and you also set the New Type to an enum value on the same field, the New Name is ignored during scaffolding,

**Comment by R4ND3LL** [comment]
Can't reproduce this one.  I may need an example (preferably from the EDMX/Rules I already have)

**Comment by jdanielpa** [comment]
I think I found a similar problem with New Name on TPH base class:
![image](https://user-images.githubusercontent.com/119625172/214683708-6230b130-2423-45e0-ac5b-1ebadf233eb2.png)

I set the New Name to 'HTMLColorDB' but after scaffolding you can see in the code it is still the Expected Property Name.

I will try to reproduce the enum path again.

**Comment by R4ND3LL** [comment]
naming issue reproduced and fixed on v1.2.13

**Comment by jdanielpa** [comment]
The fix worked.  Thanks!
