### ISSUE TITLE
Template issue with navigation property

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#17]
I have a navigation property which I expect to be nullable but it is not:

![image](https://user-images.githubusercontent.com/119625172/214723735-e1bc68bd-eee2-46be-a034-03ea0333e28f.png)

You can see the FK is nullable (MetrologyMachineID) but the related navigation property MetrologyMachine is not.

Here is the EntityType.t4 code block:

```
//************************************************************************************************************************
    foreach (var navigation in EntityType.GetNavigations())
    {
        WriteLine("");

        if (Options.UseDataAnnotations)
        {
            foreach (var dataAnnotation in navigation.GetDataAnnotations(annotationCodeGenerator))
            {
#>
    <#= code.Fragment(dataAnnotation) #>
<#
            }
        }

        var targetType = navigation.TargetEntityType.Name;
        if (navigation.IsCollection)
        {
#>
    public virtual List<<#= targetType #>> <#= navigation.Name #> { get; set; } = new List<<#= targetType #>>();
<#
        }
        else
        {
            var needsNullable = Options.UseNullableReferenceTypes && !(navigation.ForeignKey.IsRequired && navigation.IsOnDependent);
            var needsInitializer = Options.UseNullableReferenceTypes && navigation.ForeignKey.IsRequired && navigation.IsOnDependent;
#>
    public virtual <#= targetType #><#= needsNullable ? "?" : "" #> <#= navigation.Name #> { get; set; }<#= needsInitializer ? " = null!;" : "" #>
<#
        }
    }
//************************************************************************************************************************
```

Can you tell me what I am doing wrong?  I suspect it is with the needsNullable variable?

Thanks!

**Comment by R4ND3LL** [comment]
references types are inherently nullable.. but if you have nullable reference types turned on for your project, that means you want to explicitly define when things can be null or not, in order to better prevent null ref errors (but is more work overall IMO). In the project file, you'd have: 
```
<Nullable>enable</Nullable>
```
the scaffolding option "UseNullableReferenceTypes" is off by default.  enable by adding --nullable to scaffolding cmd

**Comment by jdanielpa** [comment]
I don't want to create more work than necessary :). So the issue I am having is this:

The code above is in a class (table) called MeasuredPallet.  I created a method in my engine to get all the MeasuredPallets in the database,  Currently there is only one in the database and that one has the MetrologyMachineID set to null.  In my engine, if I use the call:

`var firstMP = context.MeasuredPallets.First();`

That call results in:

System.Data.SqlTypes.SqlNullValueException: 'Data is Null. This method or property cannot be called on Null values.'

If I set the MetrologyMachine to nullable then I can make the same call without the error.  Can you tell me what is the best way to handle this without creating too much work?
 Thanks!

**Comment by R4ND3LL** [comment]
I hit the same error on your context - it was specifically related to a NULL found in the Discriminator column (as explained on another issue comment)..  Discriminator values are required in EF 7
