### ISSUE TITLE
Fix 302 validation error first

### ISSUE THREAD

**Issue by mariano-diazserviges** [R4ND3LL/EdmxRuler#19]
I'm getting this validation error because of _**DB names**_, that contain caracters such "$" or "(". Properties are well refactorized when I first run scaffold-DbContext, but this error prevents from changing rules.json file.
Will you fix it? Thanks a thillion!

![image](https://user-images.githubusercontent.com/75087022/222891315-44fbfde1-396b-4f21-ae75-80cb3fc38f90.png)

**Comment by R4ND3LL** [comment]
What DBMS are you using?  I'm surprised that you can use those characters in the column names.  I can adjust the validation to accommodate the actual allowed characters set.

**Comment by R4ND3LL** [comment]
Updated validation to support full ASCII character set.  

Update to v1.2.21 and latest VS extension

**Comment by mariano-diazserviges** [comment]
DBMS is Azure SQL. Astounding, isn't it? Not my DB, not my headaches...
Thank you very much!

**Comment by mariano-diazserviges** [comment]
Sorry, seems not solved yet. Surprinsingly to me 'ª' is allowed as naming caracter for variables, methods, etc...
![image](https://user-images.githubusercontent.com/75087022/223392840-c0d88c47-d624-494f-ac3f-5d17d17ee87a.png)

**Comment by R4ND3LL** [comment]
Relaxed the naming validation further.  Now, anything is allowed in the DB Name.  That certainly isn't considered best practice though.  

Latest build should work.

**Comment by mariano-diazserviges** [comment]
Tested and working fine. thanks!
I absolutely agree to not being this naming best practice, since it's an awful practice. But I should say that it's what you get whenever you work with Bussiness Central extensions by Microsoft, where, due to its policy naming, field captions stand for field names. In my discharge, I say my duty here is to _extend_ a third part extension from outside (you can say something of hacking but only with data). In this regard, I'd like to ask if there is any issue when defining custom FKs when you only have read permission (third part grant me only read permission). I bet it's my fault in setting the FKs in JSON file, but I cannot find the problem and I wonder if that could be, since I make valid FKs through code.

Again, thanks a lot.

**Comment by R4ND3LL** [comment]
Generally, if you have a custom foreign key defined in the EDMX then all the necessary configurations will be added to the json file.  At the root of the model, the FK itself must be defined as shown:
![image](https://user-images.githubusercontent.com/65310488/223495593-0db91e25-9370-4fb5-9ffa-23abd245b0ca.png)

Then the constraint reference should be made from the custom navigation:
![image](https://user-images.githubusercontent.com/65310488/223495705-9d1eabb5-a26b-43fa-9262-34141e608620.png)

As long as the FK is configured properly on compatible key fields it should work.  The scaffolding output (log) may indicate any issue that was encountered.
