### ISSUE TITLE
Can write Navigation Property only in one Entity in 1 to * Relationship.

### ISSUE THREAD

**Issue by zaccaromatias** [R4ND3LL/EdmxRuler#30]
Hello, first **THANK YOU VERY MUCH**, we are migrating our backend from Net 4.8 to Net 6. And therefore EntityFramework.
We currently work with Database First and many .edmx with our own t4 that generates our entities and DbContext. After the migration we should try to move to a Model First approach.
So your library is of great help, generating the json to use scafolding and thus being able to generate the models and entities according to each edmx.

The problem I find is in a 1 to * relationship, for example an Email can have 0 or many Attachments. In our model we have the Email entity with a property that is a collection of Atachment, and in Atachment only the EmailId property not the Email navigation property.

The Json that your tool generates for us looks correct, it only includes the navigation property on the Email side. And in the Atachment entity no.
`{
          "Name": "Email",
          "NewName": "Email",
          "IncludeUnknownColumns": false,
          "Properties": [
            {
              "Name": "OrganizationId"
            },
            {
              "Name": "Id"
            },
            {
              "Name": "From"
            },
            {
              "Name": "To"
            },
            {
              "Name": "Cc"
            },
            {
              "Name": "Bcc"
            },
            {
              "Name": "Subject"
            },
            {
              "Name": "IsHtml"
            },
            {
              "Name": "Body"
            },
            {
              "Name": "DateAdded"
            },
            {
              "Name": "ShipDate"
            },
            {
              "Name": "RetryCount"
            },
            {
              "Name": "ErrorMessage"
            },
            {
              "Name": "CreateUserId"
            },
            {
              "Name": "ExpirationDate"
            },
            {
              "Name": "EmailImportanceId"
            },
            {
              "Name": "EmailPriorityId"
            },
            {
              "Name": "EmailStateId"
            },
            {
              "Name": "SourceTransactionTypeId"
            },
            {
              "Name": "SourceTransactionId"
            },
            {
              "Name": "SourceTransactionNumber"
            },
            {
              "Name": "Attachments"
            },
            {
              "Name": "Timestamp"
            }
          ],
          "Navigations": [
            {
              "Name": null,
              "NewName": "EmailAttachments",
              "FkName": "FK_EmailAttachment_EmailId",
              "ToEntity": "EmailAttachment",
              "IsPrincipal": true,
              "Multiplicity": "*"
            }
          ]
        },`

`{
          "Name": "EmailAttachment",
          "NewName": "EmailAttachment",
          "IncludeUnknownColumns": false,
          "Properties": [
            {
              "Name": "Id"
            },
            {
              "Name": "EmailId"
            },
            {
              "Name": "DownloadKey"
            },
            {
              "Name": "OrganizationId"
            },
            {
              "Name": "Timestamp"
            }
          ]
        },`
But when using Scafolding it adds the navigation property to the Attachment entity. And in the DbContext you configure the relationship there..

In **Email**
`public virtual ICollection<EmailAttachment> EmailAttachments { get; set; }`
In **EmailAtachment**
`public virtual Email Email { get; set; } = null!;`
In **Context**
`modelBuilder.Entity\<EmailAttachment\>(entity =>
            {
                entity.ToTable("EmailAttachment");

                entity.HasIndex(e => e.EmailId, "IX01_EmailAttachment");

                entity.Property(e => e.Timestamp)
                    .IsRowVersion()
                    .IsConcurrencyToken();

                entity.HasOne(d => d.Email)
                    .WithMany(p => p.EmailAttachments)
                    .HasForeignKey(d => d.EmailId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_EmailAttachment_EmailId");
            });`
How can I prevent the navigation property from being added to EmailAtachment and so that in the context the relationship is configured in the Email entity as follows?
`entity
                .HasMany\<EmailAttachment\>(e => e.EmailAttachments)
                .WithOne()
                .HasForeignKey(e => e.EmailId)
                .HasConstraintName("FK_EmailAttachment_EmailId");`

Sorry for the length, and thank you very much in advance for any help.

**Comment by R4ND3LL** [comment]
EFCore requires that both ends of a relation are represented in the model for the scaffolding process.

And EFR does not provide any features for hiding a single end.

However you should be able to work around it if you have to.

One simple way could be to set the Comment on the nav you want to hide to the text "Hide".

In json you can add this property:
```json
"Annotations": {
  "Relational:Comment": "Hide"
}
```

You should know that all annotations added in json can be accessed within the t4 while code is generating.

You can then omit the property from code by placing this in the t4 within the property loop:
```csharp
var comment = property.GetComment();
if (comment == "Hide") continue;
```

This will get you most of the way there.  The entity configuration likely makes reference to the omitted property, so you will have to ammend the entity configuration by creating a partial DbContext class and implementing the partial method "**OnModelCreatingPartial**".    If you're doing entity config splitting, this will be called "**OnConfigurePartial**".

Let me know how you make out.

**Comment by zaccaromatias** [comment]
Thank you very much for responding, I will then try to customize the t4 file.
What is not clear to me is where in the Json I added that Annotation.
 Is there a page or wiki with the properties, customizations or annotations that can be made to the Json?
 
 Thank you again very much for your time.

**Comment by R4ND3LL** [comment]
Within the tag for the target property.

Alternatively, in VS install the Entity Framework Ruler extension (https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler), and use the UI editor available when you right click on the json file.
