### ISSUE TITLE
Trouble migrating from EDMX to EF Core

### ISSUE THREAD

**Issue by MisinformedDNA** [R4ND3LL/EdmxRuler#32]
I'm migrating from EF6 to EF Core 8.

Steps so far:
1. Created a new EF Core project and a new startup project, both targeting .NET 8
2. Right-clicked on the EDMX and generated rules
3. Run `dotnet ef dbcontext scaffold "Name=ConnectionStrings:Blah" "Microsoft.EntityFrameworkCore.SqlServer" -p ..\Data.EFCore\Data.EFCore.csproj -s .`

EXPECTED: 

Model is created based on rules.

ACTUAL:

Tables with no rules are created anyway. Entities with specified names (i.e. NewName) are created with EntityName instead.

```json
{
  "Name": "Entities",
  "PreserveCasingUsingRegex": false,
  "IncludeUnknownSchemas": false,
  "SplitEntityTypeConfigurations": false,
  "CaseSensitive": false,
  "Schemas": [
    {
      "SchemaName": "dbo",
      "IncludeUnknownTables": false,
      "IncludeUnknownViews": false,
      "IncludeUnknownFunctions": false,
      "Namespace": null,
      "Entities": [
        {
          "Name": "t_ASN",
          "EntityName": "TAsn",
          "NewName": "Asn",
```

```csharp
public partial class TAsn { }
```

What am I doing wrong?

**Comment by R4ND3LL** [comment]
on the scaffolded project, do you have a reference for
```
	<PackageReference Include="EntityFrameworkRuler.Design" Version="1.3.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
```
?

**Comment by MisinformedDNA** [comment]
Yep. I have it on both projects.

**Comment by R4ND3LL** [comment]
you should only require the _EntityFrameworkRuler.Design_ reference from Data.EFCore.csproj

I suspect it is because you are not running the scaffold from the folder with the rules json file.  I don't think I've done that before.

do you have a use-case that requires you to run it from another folder?

I have cases where I need context and models to be generated elsewhere, but I do it using a command like this (from the project that has the rules json file):
```
dotnet-ef dbcontext scaffold "data source=.........." Microsoft.EntityFrameworkCore.SqlServer -c ContextName -o ..\Models\Models -n MyNamespace -f --context-dir ..\Persistence\Context
```

Note, the reason for this is that scaffolding and regenerating entities often creates compile issues, and if you want to run the scaffold again, you can't unless you resolve all the compile issues.  So my preference is to create a dummy "Scaffold.csproj" project that has the rules file and a copy of enums that are in the sln, but no other dependency on any other project.  And then use the above command to direct context and models to the actual production entities project.    That way if you introduce a compile issue, it wont stop rerunning of the scaffold command.

**Comment by MisinformedDNA** [comment]
I had the rules file in the startup project instead of the scaffolding project, which then generated a new rules file in the scaffolding project. When I moved the rules file to the scaffolding project, it generated more of what I expected but I still get some errors:

- `using System.ComponentModel.DataAnnotations.Schema;` is not added to generated files (for types like `DatabaseGenerated` and `DatabaseGeneratedOption`
- In `BlahFunctions.cs`
    - Has `using Dapper;`, but this wasn't mentioned in the README
    - Methods are returning the wrong type
      > Error	CS0029	Cannot implicitly convert type 'System.Collections.Generic.List<int>' to 'int'	
      ```cs
      var response = await _context.SqlQueryRawAsync<int>("EXEC @ReturnValue = [dbo].[a_DirtyOrderReceiveUnreceiveCleanup] ", sqlParameters, cancellationToken);
      returnValue?.SetValue(pReturnValue.Value);
      return response;
      ```

In response to your last post:

It doesn't seem to matter what folder I run from, but I do need to specify a startup project; otherwise, just running from the scaffolding project results in this error:

> dotnet ef dbcontext scaffold "Name=ConnectionStrings:Blah" Microsoft.EntityFrameworkCore.SqlServer
> Build started...
> Build succeeded.
> System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
> File name: 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
>    at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
>    at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
>    at Microsoft.EntityFrameworkCore.Tools.ReflectionOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String dataDirectory, String rootNamespace, String language, Boolean nullable, String[] remainingArguments)
>    at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor(String[] remainingArguments)
>    at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute(String[] args)
>    at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0(String[] args)
>    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
>    at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
> Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)

The other thing that was throwing me off was that I get a ton of errors like "Unable to get result schema for StoredProcedure", which apparently don't matter, as they were for SPROCs that weren't in the rules file... so far as I can tell.

**Comment by R4ND3LL** [comment]
EFR attempts to read metadata about store procedures at runtime in order to provide the method calls, but complex procedures are a challenge as they often don't provide usable metadata.  It may be that the return type for the procedure couldnt be determined.  If you can create a basic mock of that procedure so I can reproduce the issue, then I can test it and provide a fix.

Regarding dapper, as per Functions.t4:
```
    var useDapper = Model.GetFunctions().Any(f => f.SupportsMultipleResultSet);
    if (useDapper) {
        usings.Add("Dapper");
        usings.Add("Microsoft.EntityFrameworkCore.Storage");
        usings.Add("System.Linq");
    }
```
Dapper can read multiple result sets, which is why it is enabled automatically for this case.  If that was detected incorrectly, then I would need another example procedure to reproduce the issue with.

**Comment by MisinformedDNA** [comment]
One of the procedures, for example, doesn't return any data. It's basically:

```sql
CREATE PROCEDURE [dbo].[Test]
AS
GO
```

And it generates:

```cs
    public virtual async Task<int> Test(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
    {
        SqlParameter pReturnValue;
        var sqlParameters = new object[]
        {
            pReturnValue = new SqlParameter
            {
                ParameterName = "ReturnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            }, 

        }; 

        var response = await _context.SqlQueryRawAsync<int>("EXEC @ReturnValue = [dbo].[Test] ", sqlParameters, cancellationToken);
        returnValue?.SetValue(pReturnValue.Value);
        return response;
    } 

```

**Comment by R4ND3LL** [comment]
that looks like the correct method.   the default return type is int for rows affected. did you test it to see if it returns 0?

**Comment by MisinformedDNA** [comment]
It doesn't compile. `SqlQueryRawAsync()` returns a `List<int>`, not an `int`.

**Comment by R4ND3LL** [comment]
I did find an issue there.  Fix applied in [EntityFrameworkRuler.Design 1.3.40](https://www.nuget.org/packages/EntityFrameworkRuler.Design/1.3.40)

Let me know if there are other issues

**Comment by MisinformedDNA** [comment]
Hmmm... I get the same error. What should have changed?

**Comment by MisinformedDNA** [comment]
I see that `isScalar` in `SqlServerProcedureFactory.Create(bool isScalar)` is unused. Could that be an issue?

```cs
internal class SqlServerProcedureFactory : RoutineFactory {
    ...
    public override DatabaseFunction Create(bool isScalar) {
        return new() { FunctionType = FunctionType.StoredProcedure };
    }
```

**Comment by R4ND3LL** [comment]
You mean you are still generating the call to ```SqlQueryRawAsync``` and returning a List?  

Its calling ```ExecuteSqlRawAsync``` for me after I made the change.  Try clearing out your project t4 files under ```CodeTemplates\EFCore\*.t4``` and let EFR recreate the T4s..  

If that doesnt work, and you have the source code checked out, you can try adjusting the factory (i.e. adding ```IsScalar = isScalar```) and testing it.  The easiest way to debug it would be to go to the project ``` Tests\NorthwindTestDesign ```  and replace the json files file with yours, and edit the scaffold.bat file and replace the connection string with yours.    Then just run ``` .\scaffold.bat ``` from a terminal.

The only issue with that approach would be it wont be able to find your system's enums, but that won't impact the scaffolding of functions.
