### ISSUE TITLE
SplitEntityTypeConfigurations enabled getting error when running SplitEntityTypeConfigurations

### ISSUE THREAD

**Issue by melucas** [R4ND3LL/EdmxRuler#7]
I successfully generated the rule file and manually updated the SplitEntityTypeConfigurations to be true.
When I run the "dotnet ef dbcontext scaffold ..." command, I receive the following error:

_You've provided an EntityTypeConfiguration.t4 file without a corresponding DbContext.t4 file. The generated DbContext code must be modified to work with your configuration classes. Provide a DbContext.t4 file and try again._

The entities and context are not generated.  However set of new folders is added to the project with a .t4 config file:
CodeTemplates -> EFCore -> EntityTypeConfiguration.t4

It looks like the DbContext.t4 file is not getting generated.

If I set SplitEntityTypeConfigurations to false, the Entities and Context are generated correctly.

My test project is a .Net 6.0 console app.  I have EntityFrameworkRuler.Design v1.17 installed with EF Core 7.0.1.

Any suggestions on getting the SplitEntityTypeConfigurations to work?

Thank you,
Michael

**Comment by R4ND3LL** [comment]
Go to https://learn.microsoft.com/en-us/ef/core/managing-schemas/scaffolding/templates?tabs=dotnet-core-cli

and follow the steps under **Adding the default templates**.   That should resolve it

**Comment by melucas** [comment]
Thanks for the quick response.  That solved my problem!
