### ISSUE TITLE
VSIX's resource loading error on not English environment. 

### ISSUE THREAD

**Issue by makotoitomeitetsucom** [R4ND3LL/EdmxRuler#9]
Konnichiwa (Hello) Mark.

I tried to read the JSON file that contains conversion rules by the extension "Edit DB Context Rules" on Visual Studio.
And then, VS displayed error dialog with the message "Can't find resource toolwindows ruleeditordialog.xaml".
(Sorry I don't remember the message exactly.)
When VS showed the dialog, VS's language environment was Japanese.
After that, I changed VS's language from Japanese to English, VS showed the dialog successfully.

It seems vsix package doesn't include ruleeditordialog.xaml file for not English environment (or VS cannot find the resource on the other lang environment).

(I tried on Visual Studio 2022 community editon , Entity Framework Ruler 1.0.85)

**Comment by R4ND3LL** [comment]
It may take me a little time to test this in a non-English environment.  I'll keep you posted.

**Comment by R4ND3LL** [comment]
Fixed in latest VSIX update
